#!/usr/bin/env node

var program = require('commander');
var trolol = require('./src/trolol.js');

program
    .version(require('./package.json').version);

program
    .command('command-not-found')
    .alias('cmd')
    .arguments('<command>')
    .description('Overwrite command with a fake alias')
    .action(trolol.commandNotFound);

program
    .command('rebecca-black')
    .alias('rebecca')
    .option('-s, --saturday', 'Play "Saturday by Rebecca Black"')
    .option('-w, --wait <seconds>', 'Wait with the troll', parseInt)
    .description('Play Rebecca Black Greatest Hits in a browser ("Friday" is default)')
    .action(trolol.rebecca);

program
    .command('steve')
    .option('-w, --wait <seconds>', 'Wait with the troll', parseInt)
    .description('Open "Developers by Steve Balmer" in a browser')
    .action(trolol.steve);

program
    .command('volume-level')
    .alias('vol')
    .arguments('<length>')
    .option('-w, --wait <seconds>', 'Wait with the troll', parseInt)
    .description('Change volume level randomly in period of time (length in seconds)')
    .action(trolol.volumeLevel);

program
    .command('brightness')
    .arguments('<length>')
    .option('-w, --wait <seconds>', 'Wait with the troll', parseInt)
    .description('Change brightness randomly in period of time (length in seconds)')
    .action(trolol.brightness);

program
    .command('screensaver')
    .arguments('<times>')
    .option('-w, --wait <seconds>', 'Wait with the troll', parseInt)
    .description('Start the screensaver with a random interval of 5 to 30 seconds')
    .action(trolol.screensaver);

program
    .command('move-mouse')
    .alias('mouse')
    .arguments('<length>')
    .option('-w, --wait <seconds>', 'Wait with the troll', parseInt)
    .description('Move mouse slowly and randomly across the screen')
    .action(trolol.moveMouse);

program
    .command('disable-mouse')
    .arguments('<length>')
    .option('-w, --wait <seconds>', 'Wait with the troll', parseInt)
    .description('Disable mouse cursor for some time (length in seconds)')
    .action(trolol.disableMouse);

program
    .command('beep')
    .arguments('<times>')
    .option('-w, --wait <seconds>', 'Wait with the troll', parseInt)
    .description('Beeep beeeeep, annoying little sh*t')
    .action(trolol.beep);

program
    .command('eject')
    .arguments('<times>')
    .option('-w, --wait <seconds>', 'Wait with the troll', parseInt)
    .description('Eject media from drive after every 15 seconds n time')
    .action(trolol.eject);

program
    .command('say')
    .arguments('<message>')
    .option('-s, --scary', 'Make the voice whisper')
    .option('-w, --wait <seconds>', 'Wait with the troll', parseInt)
    .description('[MAC ONLY] Scare the sh*t out of your dude with a speaking computer')
    .action(trolol.say);

program
    .command('mmm')
    .option('-c, --cycles <integer>', 'Repeat for <integer> cycles', parseInt)
    .option('-r, --rest <seconds>', 'Rest <seconds> between mmms', parseInt)
    .option('-w, --wait <seconds>', 'Wait with the troll', parseInt)
    .option('-v, --voice <string>', 'Select a system voice')
    .description('[MAC ONLY] Receive repeated approval from your computer')
    .action(trolol.mmm);

program
    .command('photo-booth')
    .arguments('<times>')
    .option('-w, --wait <seconds>', 'Wait with the troll', parseInt)
    .description('[MAC ONLY] Open up Photo booth n times')
    .action(trolol.photoBooth);

program
    .command('spotify')
    .arguments('<times>')
    .option('-w, --wait <seconds>', 'Wait with the troll', parseInt)
    .description('[MAC ONLY] Switch Spotify music track back after every 15 seconds n time')
    .action(trolol.spotify);

program
    .command('website')
    .arguments('<from> <to>')
    .description('[RUN AS ADMIN] Redirect webpage to a different site')
    .action(trolol.website);

program
    .command('motd-dickbutt')
    .alias('dickbutt')
    .description('[RUN AS ADMIN] Add Dickbutt ASCII art text to Terminal Message of the day')
    .action(trolol.dickbutt);

program
    .command('shutdown')
    .arguments('<program>')
    .option('-t, --times <integer>', 'How many times the app "crashes"', parseInt)
    .option('-w, --wait <minutes>', 'Minimum minutes between crashes', parseInt)
    .option('-r, --range <minutes>', 'Variety in minutes between crashes', parseInt)
    .description('Quit a program every [wait] to [wait+random] minutes')
    .action(trolol.shutdown);

program.parse(process.argv);

if (!program.args.length)
    program.help();
