#!/usr/bin/env node

var program = require('commander');
var trolol = require('./src/trolol.js');

program
    .version(require('./package.json').version);

program
    .command('website')
    .arguments('<from> <to>')
    .description('[RUN AS ADMIN] Redirect webpage to a different site')
    .action(trolol.website);

program
    .command('command-not-found')
    .alias('cmd')
    .arguments('<command>')
    .description('Overwrite command with a fake alias')
    .action(trolol.commandNotFound);

program
    .command('friday')
    .option('-w, --wait <seconds>', 'Wait with the troll', parseInt)
    .description('Open "Friday by Rebecca Black" in a browser')
    .action(trolol.friday);

program
    .command('steve')
    .option('-w, --wait <seconds>', 'Wait with the troll', parseInt)
    .description('Open "Developers by Steve Balmer" in a browser')
    .action(trolol.steve);

program
    .command('volume-level')
    .alias('vol')
    .arguments('<length>')
    .option('-w, --wait <seconds>', 'Wait with the troll', parseInt)
    .description('[MAC ONLY] Change volume level randomly in period of time (length in seconds)')
    .action(trolol.volumeLevel);

program
    .command('brightness')
    .arguments('<length>')
    .option('-w, --wait <seconds>', 'Wait with the troll', parseInt)
    .description('Change brightness randomly in period of time (length in seconds)')
    .action(trolol.brightness);

program
    .command('move-mouse')
    .alias('mouse')
    .arguments('<length>')
    .option('-w, --wait <seconds>', 'Wait with the troll', parseInt)
    .description('Move mouse slowly and randomly across the screen')
    .action(trolol.moveMouse);

program
    .command('disable-mouse')
    .arguments('<length>')
    .option('-w, --wait <seconds>', 'Wait with the troll', parseInt)
    .description('Disable mouse cursor for some time (length in seconds)')
    .action(trolol.disableMouse);

program
    .command('say')
    .arguments('<message>')
    .option('-s, --scary', 'Make the voice whisper')
    .option('-w, --wait <seconds>', 'Wait with the troll', parseInt)
    .description('[MAC ONLY] Scare the sh*t out of your dude with a speaking computer')
    .action(trolol.say);

program
    .command('beep')
    .arguments('<times>')
    .option('-w, --wait <seconds>', 'Wait with the troll', parseInt)
    .description('Beeep beeeeep, annoying little sh*t')
    .action(trolol.beep);

program
    .command('photo-booth')
    .arguments('<times>')
    .option('-w, --wait <seconds>', 'Wait with the troll', parseInt)
    .description('[MAC ONLY] Open up Photo booth n times')
    .action(trolol.photoBooth);

program
    .command('spotify')
    .arguments('<times>')
    .option('-w, --wait <seconds>', 'Wait with the troll', parseInt)
    .description('[MAC ONLY] Switch Spotify music track back after every 15 seconds n time')
    .action(trolol.spotify);

program
    .command('eject')
    .arguments('<times>')
    .option('-w, --wait <seconds>', 'Wait with the troll', parseInt)
    .description('Eject media from drive after every 15 seconds n time')
    .action(trolol.eject);

program.parse(process.argv);
